
class Constants:

   RICHNESS_NULL = 0
   RICHNESS_POOR = 1
   RICHNESS_OK = 2
   RICHNESS_LUSH = 3

   TREE_SEED = 0
   TREE_SMALL = 1
   TREE_MEDIUM = 2
   TREE_TALL = 3

   TREE_BASE_COST = [ 0, 1, 3, 7 ]
   TREE_COST_SCALE = 1
   LIFECYCLE_END_COST = 4
   DURATION_ACTION_PHASE = 1000
   DURATION_GATHER_PHASE = 2000
   DURATION_SUNMOVE_PHASE = 1000
   STARTING_TREE_COUNT = 2
   RICHNESS_BONUS_OK = 2
   RICHNESS_BONUS_LUSH = 4
